export const Products = [
  {
    id: 1,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title:
      'Box Type Compressor Condensing Unit, 2HP-15HP for Refrigeration Cold Room',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948966/4_l4zxys.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948967/5_dt0d1s.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948967/1_g26baq.jpg',
    },
  },
  {
    id: 2,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/Amchiller-800x450_ypzq0z.jpg',
    catgeory: 'featured',
    title: 'Dl Model Unit Cooler Evaporator for Cold Room Storage',
    price: 100,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/Amchiller-800x450_ypzq0z.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948966/4_l4zxys.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948967/5_dt0d1s.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948967/1_g26baq.jpg',
    },
  },
  {
    id: 3,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
    catgeory: 'featured',
    title: 'V Box Type Condenser Condensing Unit for Freezer Room',
    price: 200,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/Amchiller-800x450_ypzq0z.jpg',
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948966/4_l4zxys.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948967/5_dt0d1s.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948967/1_g26baq.jpg',
    },
  },
  {
    id: 4,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title:
      'Box Type Compressor Condensing Unit, 2HP-15HP for Refrigeration Cold Room',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948966/4_l4zxys.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948967/5_dt0d1s.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691948967/1_g26baq.jpg',
    },
  },
  {
    id: 5,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title:
      'Box Type Compressor Condensing Unit, 2HP-15HP for Refrigeration Cold Room',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 6,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/Amchiller-800x450_ypzq0z.jpg',
    catgeory: 'featured',
    title: 'Dl Model Unit Cooler Evaporator for Cold Room Storage',
    price: 100,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 7,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
    catgeory: 'featured',
    title: 'V Box Type Condenser Condensing Unit for Freezer Room',
    price: 200,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 8,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title:
      'Box Type Compressor Condensing Unit, 2HP-15HP for Refrigeration Cold Room',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 9,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title:
      'Box Type Compressor Condensing Unit, 2HP-15HP for Refrigeration Cold Room',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
  },
  {
    id: 10,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/Amchiller-800x450_ypzq0z.jpg',
    catgeory: 'featured',
    title: 'Dl Model Unit Cooler Evaporator for Cold Room Storage',
    price: 100,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 11,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
    catgeory: 'featured',
    title: 'V Box Type Condenser Condensing Unit for Freezer Room',
    price: 200,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 12,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title:
      'Box Type Compressor Condensing Unit, 2HP-15HP for Refrigeration Cold Room',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 13,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title:
      'Box Type Compressor Condensing Unit, 2HP-15HP for Refrigeration Cold Room',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 14,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/Amchiller-800x450_ypzq0z.jpg',
    catgeory: 'featured',
    title: 'Dl Model Unit Cooler Evaporator for Cold Room Storage',
    price: 100,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 15,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
    catgeory: 'featured',
    title: 'V Box Type Condenser Condensing Unit for Freezer Room',
    price: 200,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
  {
    id: 16,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title:
      'Box Type Compressor Condensing Unit, 2HP-15HP for Refrigeration Cold Room',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
    image: {
      img1: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img2: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img3: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img4: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
      img5: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    },
  },
];
export const Sliderimages = [
  {
    id: 1,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
  },
  {
    id: 2,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/Amchiller-800x450_ypzq0z.jpg',
  },
  {
    id: 3,
    photo:
    'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
  },
  {
    id: 4,
    photo:
      'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
  },
];
