const Products = [
  {
    id: 1,
    photo: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_four_t7xd2w.jpg',
    catgeory: 'featured',
    title: 'Product one',
    price: 90,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
  },
  {
    id: 4,
    photo: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/Amchiller-800x450_ypzq0z.jpg',
    catgeory: 'featured',
    title: 'Product two',
    price: 100,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
  },
  {
    id: 3,
    photo: 'https://res.cloudinary.com/dagjuuf4v/image/upload/v1691177742/JustCold/slider_image_one_cffqgm.jpg',
    catgeory: 'featured',
    title: 'Product three',
    price: 200,
    type: 'Air-Cooled',
    Certification: 'RoHS, ISO, CE',
    FansSpecies: 'Axial Fan',
    ApplicationFields: 'Cold Room, Cold Storage, Freezer Room',
    Condition: 'new',
    Customization: 'Available',
  },
];
export default Products;
